### PR TITLE
Add support for clickable links in chat messages

### PR DESCRIPTION
**Pull request by business-goose**

### CODE REVIEW

**Comment by Apmunute** [comment]
Please

**Comment by TFTWPhoenix** [comment]
@mathiascode there is no good reason to not merge this.

**Comment by business-goose** [comment]
شيي سعححخقف بخق ؤمهؤنشلامث مهىنس هى ؤاشف ةثسسشلثس

**Comment by Apmunute** [comment]
mathias... please delete racoon.pw

**Comment by business-goose** [comment]
> mathias... please delete racoon.pw

when نشلاخخة سثقرثق racoon.pw

**Comment by mathiascode** [comment]
Seems like a recent issue that should be reported to Paper.

**Comment by TFTWPhoenix** [comment]
@mathiascode bruh.

**Comment by business-goose** [comment]
> Seems like a recent issue that should be reported to Paper.

Reported in https://github.com/PaperMC/Paper/issues/5279

**Comment by business-goose** [comment]
Seems like a "patch" may be to downgrade to paper 418, however that may bring back some crashes. Not exactly recommended.

**Pull request closed without merging**
