### PR TITLE
Patch Kaboom Whitelist

### PR DESCRIPTION
**Pull request by 800733c869f0e5aa3c65**

### CODE REVIEW

**Comment by TFTWPhoenix** [comment]
@mathiascode no good reason to not merge this. KBWL is super annoying.

**Comment by Apmunute** [comment]
same

**Comment by Apmunute** [comment]
please merge this, kbwl is retarded... i want to play on kaboom :sob:

**Comment by TFTWPhoenix** [comment]
bump

**Comment by Apmunute** [comment]
matty... please merge

**Comment by TFTWPhoenix** [comment]
@mathiascode @mathiascode @mathiascode @mathiascode @mathiascode @mathiascode @mathiascode MERGE ITTT

**Pull request closed without merging**
